### ISSUE TITLE
Tags or auto sync optional

### ISSUE THREAD

**Issue by XenorPLxx** [SparrowBrain/Playnite.GGDeals#16]
Hi,
When I'm importing new games I'm using a dedicated saved filter to see games that have no tags, categories and completion statuses - this is a 'new' game in my Playnite (i dont sync any of these when doing metadata download, i use my own tags etc.)
With this plugin, games are automatically synced and tagged, which messes up with my 'new' saved filter.
Is it possible to add a configuration option to skip adding tags? Or, if tags are used internally, can there be an option to not sync automatically?

**Comment by SparrowBrain** [comment]
Yes to both.

On my planned list of features.

**Comment by SparrowBrain** [comment]
Should be solved with v2.1.0. Now:
* tags are optional
* automatic syncing of newly added games is optional
Let me know, if it works for you :)

**Comment by XenorPLxx** [comment]
Yea, working great for me, thank :)
