### ISSUE TITLE
Better integration with GG.deals

### ISSUE THREAD

**Issue by rob006** [SparrowBrain/Playnite.GGDeals#4]
Hi, I'm a lead developer at GG.deals. Could you contact with me using [our contact form](https://gg.deals/contact/) (use "technical issues" as subject)? I'd like to discuss potential improvements to this extension.

**Comment by XenorPLxx** [comment]
Just wanted to say that this extension is fire!

I was thinking of doing something similar (as a part of Sharenite extension), but having it directly in Playnite and with official support from GG.deals is even better :).

**Comment by SparrowBrain** [comment]
API implemented with v2.0.0. Thanks @rob006
